volumes:
  cache:
  words:

services:

  tagger:
    image: srcml/scanl_tagger
    build:
      context: ./
      platforms:
        - ${BUILD_PLATFORM:-linux/arm64}
        - ${BUILD_PLATFORM:-linux/amd64}
    volumes:
      - cache:/app/cache
      - words:/app/words
    ports:
      - "${PORT-8080}:8080"
    restart: always
