volumes:
  vectors:

services:

  tagger:
    image: srcml/scanl_tagger
    build:
      context: ./
      platforms:
        - "linux/arm64"
        - "linux/amd64"
    volumes:
      - vectors:/code2vec
    ports:
      - "8080:5000"
