volumes:
  vectors:
  gensim:
  cache:

services:

  tagger:
    image: srcml/scanl_tagger
    build:
      context: ./
      platforms:
        - ${BUILD_PLATFORM:-linux/arm64}
        - ${BUILD_PLATFORM:-linux/amd64}
    volumes:
      - vectors:/code2vec
      - gensim:/root/gensim-data
      - cache:/cache
    ports:
      - "${PORT-8080}:5000"
