volumes:
  vectors:
  gensim:

services:

  tagger:
    image: srcml/scanl_tagger
    build:
      context: ./
      platforms:
        - "linux/arm64"
        - "linux/amd64"
    volumes:
      - vectors:/code2vec
      - gensim:/root/gensim-data
    ports:
      - "${PORT-8080}:5000"
