name: SCALAR Tagger CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Start Docker container
        run: |
          docker compose pull
          docker compose up -d
      
      - name: Wait for service to start
        run: sleep 300
      
      - name: Test tagger endpoint
        run: |
          response=$(curl -s "http://localhost:8080/cache/numberArray/DECLARATION")
          if [ -z "$response" ]; then
            echo "No response from tagger"
            exit 1
          fi
          echo "Received response: $response"

  test-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Create and activate virtual environment
        run: |
          python -m venv /tmp/tagger
          source /tmp/tagger/bin/activate
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Start tagger server
        run: |
          ./main -r
          sleep 10
      
      - name: Test tagger endpoint
        run: |
          response=$(curl -s "http://localhost:5000/cache/numberArray/DECLARATION")
          if [ -z "$response" ]; then
            echo "No response from tagger"
            exit 1
          fi
          echo "Received response: $response"